#  Copyright (C) 2019 Knot.x Project
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

openapi: "3.0.0"
info:
  version: 1.0.0
  title: Knot.x Stack OAS
  description: This is a full flow server used during integration tests.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
- url: https://{domain}:{port}
  description: The local API server
  variables:
    domain:
      default: localhost
      description: api domain
    port:
      enum:
        - '8092'
        - '443'
      default: '8092'

paths:
  /content/*:
    get:
      operationId: te-get
      responses:
        default:
          description: HTTP repository response continaing fragments with
            Data Bridge (https://github.com/Knotx/knotx-data-bridge) and
            Template Engine (https://github.com/Knotx/knotx-template-engine) processing
  /api/author-info:
    get:
      operationId: author-info
      responses:
        default:
          description: Gateway API endpoint that uses Data Bridge (https://github.com/Knotx/knotx-data-bridge)
  /api/ecommerce/checkout:
    get:
      operationId: checkout-operation
      responses:
        default:
          description: Endpoint which uses HttpAction