sudo: required
language: java
install: true
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package -Pskip-integration-tests
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9f543ed555acc6226fe5
    on_success: always
    on_failure: always
    on_start: never
