# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/Knotx/knotx-aggregator.git
    mkdir modules
  displayName: "Prepare Knot.x Aggregator"
- task: CmdLine@2
  inputs:
    script: |
      cd knotx-aggregator/development
      ./pull-all.sh -r ../../modules -b $(Build.SourceBranchName) -a
  displayName: "Clone all Knot.x repositories"
- task: CmdLine@2
  inputs:
    script: |
      cd knotx-aggregator/development
      ./build-all.sh -r ../../modules
  displayName: "Build Knot.x Stack"
- script: |
    cd modules/knotx-docker
    mvn clean package
  displayName: "Build Docker image"
