# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Knot.x Stack"
    git clone https://github.com/Knotx/knotx-aggregator.git
    cd knotx-aggregator/development
    mkdir modules
    ./pull-all.sh -r modules -b $(Build.SourceBranchName) -a $(System.AccessToken)
    ./build-all.sh -r modules -d