/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.4.1/userguide/multi_project_builds.html
 */

rootProject.name = "knotx-stack"

includeBuild("../knotx-commons")
includeBuild("../knotx-launcher")
includeBuild("../knotx-junit5")
includeBuild("../knotx-fragment-api")
includeBuild("../knotx-server-http")
includeBuild("../knotx-repository-connector")
includeBuild("../knotx-fragments-handler")
includeBuild("../knotx-data-bridge")
includeBuild("../knotx-template-engine")